### ISSUE TITLE
Strings in BPF code break relocations

### ISSUE THREAD

**Issue by rsdy** [redsift/ingraind#21]
```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .strtab           STRTAB           0000000000000000  000002a0
       0000000000000085  0000000000000000           0     0     1
  [ 2] .text             PROGBITS         0000000000000000  00000040
       0000000000000000  0000000000000000  AX       0     0     4
  [ 3] xdp/dns_queries   PROGBITS         0000000000000000  00000040
       0000000000000038  0000000000000000  AX       0     0     8
  [ 4] .relxdp/dns_queri REL              0000000000000000  00000280
       0000000000000010  0000000000000010          11     3     8
  [ 5] maps/dns_queries  PROGBITS         0000000000000000  00000078
       0000000000000118  0000000000000000  WA       0     0     4
  [ 6] version           PROGBITS         0000000000000000  00000190
       0000000000000004  0000000000000000  WA       0     0     4
  [ 7] license           PROGBITS         0000000000000000  00000194
       0000000000000004  0000000000000000  WA       0     0     1
  [ 8] .rodata.str1.1    PROGBITS         0000000000000000  00000198
       000000000000000b  0000000000000001 AMS       0     0     1
  [ 9] .eh_frame         PROGBITS         0000000000000000  000001a8
       0000000000000030  0000000000000000   A       0     0     8
  [10] .rel.eh_frame     REL              0000000000000000  00000290
       0000000000000010  0000000000000010          11     9     8
  [11] .symtab           SYMTAB           0000000000000000  000001d8
       00000000000000a8  0000000000000018           1     3     8
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

There are no section groups in this file.

There are no program headers in this file.

There is no dynamic section in this file.

Relocation section '.relxdp/dns_queries' at offset 0x280 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name
000000000008  000100000001 unrecognized: 1       0000000000000000 .L.str

Relocation section '.rel.eh_frame' at offset 0x290 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name
00000000001c  000200000001 unrecognized: 1       0000000000000000 xdp/dns_queries

The decoding of unwind sections for machine type Linux BPF is not currently supported.

Symbol table '.symtab' contains 7 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    8 .L.str
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT    3
     3: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    7 _license
     4: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    6 _version
     5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    5 dns_queries
     6: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    3 report_dns_queries
```

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Reloc', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: ingraind::main::{{closure}}
             at src/main.rs:89
```

```
SEC("xdp/dns_queries")
int report_dns_queries(struct xdp_md *ctx)
{
	u64 pid = bpf_get_current_pid_tgid();

	struct ethhdr *eth = (struct ethhdr *)(long)ctx->data;
	__u16 proto;

  bpf_trace_printk("lofasz %ll", pid);

	proto = eth->h_proto;
	if (proto == bpf_htons(ETH_P_IP))
		return XDP_DROP;
	else if (proto == bpf_htons(ETH_P_IPV6))
		return XDP_DROP;
	else
		/* Pass the rest to stack, we might later do more
		 * fine-grained filtering here.
		 */
    return XDP_DROP;
};
```

**Comment by jeromegn** [comment]
Is there a solution to this?

**Comment by rsdy** [comment]
This is a stale issue, and I don't have a case at the moment where this would be a constrain since we moved all probes to Rust. With Rust-based probes we can automatically convert strings to byte arrays using `b"string"`, which means strings will be part of the application segment, so this issue doesn't exist anymore.

If you can share your specific usecase, I might be able to look into that.

**Comment by jeromegn** [comment]
:+1: I just didn't know I should've been making byte slices out of my strs instead :)

That makes me think of another question: if there's a way to log debug strings (or byte slices)? I remember something about being able to send logs to sys fs tracepipe from a bpf program.

**Comment by rsdy** [comment]
You should be able to use https://ingraind.org/api/redbpf_probes/helpers/fn.bpf_trace_printk.html for this purpose. Please open a separate issue here or at https://github.com/redsift/redbpf if you have any trouble using it, though, because I don't think we've tested it thoroughly enough.

I'll close this now, thanks for picking up on it!
